In [1]:
import pandas as pd
import numpy as np

In [2]:
label_csv_path = "/Users/tanmaygoyal/Desktop/Assignments and Events/Biomedicine/ECG_Project/data/PTB_XL/labels.csv"
label_csv = pd.read_csv(label_csv_path , dtype={'patient_id':str})

In [3]:
label_csv

,patient_id,NORM,LVH,INJAS,WPW,ISCIL,ISC_,ANEUR,ILBBB,ISCAS,...,INJIL,LPFB,ALMI,PAC,CLBBB,BIGU,INJAL,AFLT,INJIN,AFIB
0,00001,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,00002,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,00003,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,00004,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,00005,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21794,21833,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21795,21834,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21796,21835,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21797,21836,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21798,21837,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
labels_to_remove = ['ISCIN','ISCIL','DIG','ISCLA','RVH','LNGQT','EL','ISCAN','SEHYP','STACH','RAO/RAE']

In [5]:
label_csv.drop(labels_to_remove , axis = 1 , inplace = True)

In [6]:
label_csv

,patient_id,NORM,LVH,INJAS,WPW,ISC_,ANEUR,ILBBB,ISCAS,PVC,...,INJIL,LPFB,ALMI,PAC,CLBBB,BIGU,INJAL,AFLT,INJIN,AFIB
0,00001,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,00002,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,00003,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,00004,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,00005,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21794,21833,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21795,21834,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21796,21835,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
21797,21836,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21798,21837,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
potential_diseases = [c for c in label_csv.columns if c != 'patient_id']
potential_diseases

['NORM',
 'LVH',
 'INJAS',
 'WPW',
 'ISC_',
 'ANEUR',
 'ILBBB',
 'ISCAS',
 'PVC',
 'IRBBB',
 'ISCAL',
 'PACE',
 '3AVB',
 'ILMI',
 'LMI',
 'CRBBB',
 'AMI',
 '2AVB',
 'ASMI',
 '1AVB',
 'PMI',
 'NDT',
 'IVCD',
 'INJLA',
 'IPLMI',
 'IPMI',
 'IMI',
 'NST_',
 'LAFB',
 'PSVT',
 'LAO/LAE',
 'INJIL',
 'LPFB',
 'ALMI',
 'PAC',
 'CLBBB',
 'BIGU',
 'INJAL',
 'AFLT',
 'INJIN',
 'AFIB']

In [8]:
patient_ids_to_remove = label_csv[label_csv[potential_diseases].sum(axis = 1) == 0]['patient_id']

In [9]:
remove_data_path = "/Users/tanmaygoyal/Desktop/Assignments and Events/Biomedicine/ECG_Project/data/PTB_XL/removed_data.txt"
with open(remove_data_path , 'w') as f:
    for p in patient_ids_to_remove:
        f.write(p + '.mat\n')

In [10]:
label_csv.drop(label_csv[label_csv['patient_id'].isin(patient_ids_to_remove)].index , axis = 0 , inplace = True)

In [11]:
label_csv.shape

(21541, 42)

In [12]:
label_mapping = pd.read_csv("/Users/tanmaygoyal/Desktop/Assignments and Events/Biomedicine/ECG_Project/data/PTB_XL/label_mapping.csv")

In [13]:
ptb_xl_disease = label_mapping['PTB_XL'].tolist()
cpsc_disease = label_mapping['CPSC'].tolist()

In [22]:
final_label_csv = label_csv['patient_id'].to_frame()

unique_cpsc_diseases = list(set(cpsc_disease))

for disease in unique_cpsc_diseases:
    final_label_csv[disease] = 0
    for ptbxl,cpsc in zip(ptb_xl_disease,cpsc_disease):
        if cpsc == disease and ptbxl in label_csv.columns:
            all_with_label1 = label_csv[label_csv[ptbxl] == 1]['patient_id'].tolist()  
            final_label_csv.loc[final_label_csv['patient_id'].isin(all_with_label1) ,disease] = 1

In [23]:
final_label_csv[unique_cpsc_diseases].sum(axis = 0)

RBBB     1735
STD       728
IAVB     1536
SNR     14373
STE      5469
AF        207
LBBB     2231
PVC      1027
PAC       324
dtype: int64

In [24]:
final_label_csv.shape

(21541, 10)

In [25]:
final_label_csv.to_csv("/Users/tanmaygoyal/Desktop/Assignments and Events/Biomedicine/ECG_Project/data/PTB_XL/labels_final_mapping.csv" , index = False)